name: Get git info
description: Get and manipulate info from github context
inputs:
  quiet:
    description: Skip printing gathered info
    required: false
    default: false
  nexus_base_path:
    description: Base URL to Sonatype Nexus artifact storage (overrides NEXUS_BASE_PATH environment variable)
    required: false
  maven_group_id:
    description: Maven group ID (overrides MAVEN_GROUP_ID environment variable)
    required: false
  maven_artifact_id:
    description: Maven artifact ID (overrides MAVEN_ARTIFACT_ID environment variable)
    required: false
  maven_extension:
    description: Maven artifact extension to search for (overrides MAVEN_EXTENSION environment variable)
    required: false
outputs:
  sha:
    description: Long commit id
  sha_short:
    description: Short commit id (as in `git rev-parse --short HEAD`)
  tag:
    description: Tag name if the workflow has been triggered by a tag
  is_tag:
    description: Boolean set to `true` if `tag` is defined
  revision:
    description: Equals `tag` stripped by leading 'v' if `is_tag`, `sha_short` otherwise
  branch:
    description: Name of the current branch (if not `is_tag`)
  branch_unslashed:
    description: Name of the current branch with `/`s replaced by `-`s 
  repository_name:
    description: Name of the current repository
runs:
  using: 'node12'
  main: 'dist/index.js'
