name: units-test
on:
  pull_request:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:

  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  test:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Normal run
      uses: ./
      id: normal

    - name: Quiet run
      uses: ./
      id: quiet
      with:
        quiet: true

    - name: Print info from 'normal'
      run: |
        echo "sha=${{ steps.normal.outputs.sha }}"
        echo "sha_short=${{ steps.normal.outputs.sha_short }}"
        echo "tag=${{ steps.normal.outputs.tag }}"
        echo "is_tag=${{ steps.normal.outputs.is_tag }}"
        echo "revision=${{ steps.normal.outputs.revision }}"
        echo "branch=${{ steps.normal.outputs.branch }}"
        echo "repository_name=${{ steps.normal.outputs.repository_name }}"

    - name: Print info from 'quiet'
      run: |
        echo "sha=${{ steps.quiet.outputs.sha }}"
        echo "sha_short=${{ steps.quiet.outputs.sha_short }}"
        echo "tag=${{ steps.quiet.outputs.tag }}"
        echo "is_tag=${{ steps.quiet.outputs.is_tag }}"
        echo "revision=${{ steps.quiet.outputs.revision }}"
        echo "branch=${{ steps.quiet.outputs.branch }}"
        echo "repository_name=${{ steps.normal.outputs.repository_name }}"
